composer.json
Allow Symfony2 standard to be installed via composer. To install this standard, do the following:
1. Add a repository to your projects composer.json.
```
"repositories": [
{"type": "vcs","url":  "git@github.com:escapestudios/Symfony2-coding-standard.git"}
],
```
2. Install the standard.  
` composer require escapestudios/symfony2-coding-standard`
3. Add the standard to phpcs' installed_paths'.  
`bin/phpcs --config-set installed_paths ../../escapestudios/symfony2-coding-standard/escapestudios/phpcs/`
4. Have fun...  
`bin/phpcs --standard=Symfony2 ./`
_To be able to skip the first step, escapestudios should add this project to packagist.org._
=> Composerified

composer.json
This isn't needed any more now that  we're nesting the standard under
the Symfony2 directory. The target-dir directive is used to nest the
project under the composer chosen location. By default, this will be
'escapestudios/symfony2-coding-standard', so having this directive with
that same path will result in the code path being
'escapestudios/symfony2-coding-standard/escapestudios/symfony2-coding-standard'.
This directive was only really useful before we nested the standard
under the Symfony2 directory, as it allowed us to add "Symfony2" to the
destination path, allowing PHP_CodeSniffer to find the standard automatically
based on the folder name when setting the "installed_paths" config.
=> Remove deprecated target-dir directive from composer.json

README.md, composer.json
Added details for installation both globally and as a part of a project.
Also added a nice bit about using the Symfony2 standard as part of a Symfony2 project. It's not as easy as it would seem. With the method outlined in the README, you can remove the following line from the standard's ``ruleset.xml``, as it doesn't belong as part of the standard, but is rather project specific (You can still use the Symfony2 standard on a project that isn't Symfony2, right?)
<exclude-pattern>*/Resources/*</exclude-pattern>
Sorry there's like 12 commits to update this. I was all over the place and editing from the GitHub interface.
=> Update readme with more detailed description of installation and usage

Symfony2/Sniffs/Arrays/MultiLineArrayCommaSniff.php, Symfony2/Tests/Arrays/MultiLineArrayCommaUnitTest.inc, Symfony2/Tests/Arrays/MultiLineArrayCommaUnitTest.php
=> Make MultiLineArrayCommaSniff work for the short-array syntax '[]'

Symfony2/ruleset.xml
This rules cause problem with some Symfony bundle generated code like sonata-admin.
Here an example.
```php
protected function configureListFields(ListMapper $listMapper)
{
$listMapper
->add('ref')
->add('isValid')
->add('_action', 'actions', array(
'actions' => array(
'show'      => array(),
'edit'      => array(),
)
))
;
}
```
This will throw the following error 'Space after closing parenthesis of function call prohibited'.
But this is not prohibited on Symfony2 coding standards.
Already made and accepted on an another similar project: https://github.com/leaphub/phpcs-symfony2-standard/pull/1
=> Deactivate SpaceAfterCloseBracket PEAR Rule

Symfony2/Sniffs/Objects/ObjectInstantiationSniff.php, Symfony2/Tests/Objects/ObjectInstantiationUnitTest.inc, Symfony2/Tests/Objects/ObjectInstantiationUnitTest.php
the sniff reported an error on
```php
$foo = "\\a\\b\\c";
$bar = new $foo("baz");
```
it did not report an error on
```php
$foo = new $bar;
```
the pr is fixing both
=> fixed failing ObjectInstantiationSniff on variable class names

Symfony2/Sniffs/WhiteSpace/AssignmentSpacingSniff.php
I just copied the BinaryOperatorSpacingSniff into AssignmentSpacingSniff and registered for the assignmentTokens.
=> Add the sniff for whitespaces around assignment operators

Symfony2/Sniffs/NamingConventions/ValidClassNameSniff.php
This makes it possible to ignore certain invalid class names, but keep on checking for others.
For example:
<rule ref="Symfony2.NamingConventions.ValidClassName.InvalidAbstractName">
<exclude-pattern>*</exclude-pattern>
</rule>
This will ignore all errors saying that abstract class names should be prefixed with "Abstract", but keeps on checking that interfaces are suffixed with Interface, etc.
I know that abstract classes should always be prefixed with Abstract in Symfony2, but this just makes it easier for those of us who want to create their own ruleset for other projects.
We use a lot of the Symfony2 rules in our Silex projects for example, but don't always want to prefix all of our abstract classes with Abstract.
=> Made the error codes for invalid class names more specific.

.travis.yml
* Remove HHVM and PHP7 from allowed failure (it works!)
* Remove unsupported HHVM nightly: https://travis-ci.org/escapestudios/Symfony2-coding-standard/jobs/93497660#L70
=> Travis fix and improve

Symfony2/Sniffs/Objects/ObjectInstantiationSniff.php, Symfony2/Tests/Objects/ObjectInstantiationUnitTest.inc, Symfony2/Tests/Objects/ObjectInstantiationUnitTest.php
Instantiating objects using static (e.g. `$obj = new static();`) can be useful when we want to create object of called class. Symfony2 standard does not forbid this, but symfony2 standard checker shows
"Use parentheses when instantiating classes" error even if parentheses are used.
Also code like `$obj = static;` is not causing any error.
This pull request fix this.
=> Object instantiation by static

Symfony2/Sniffs/Classes/PropertyDeclarationSniff.php, Symfony2/Sniffs/Functions/ScopeOrderSniff.php
* PHP Notice: Undefined index: scope_closer in /usr/share/pear/PHP/CodeSniffer/Standards/Symfony2/Sniffs/Classes/PropertyDeclarationSniff.php on line 63
* PHP Notice: Undefined index: scope_closer in /usr/share/pear/PHP/CodeSniffer/Standards/Symfony2/Sniffs/Functions/ScopeOrderSniff.php on line 79
=> Fix PHP notices

Symfony2/Sniffs/Objects/ObjectInstantiationSniff.php, Symfony2/Tests/Commenting/FunctionCommentUnitTest.inc
FunctionCommentUnitTest required comments for function arguments
ObjectInstantiationSniff did not process "new self" instructions
=> Fix broken tests

composer.json
I removed the support info, because Composer guesses them from the Github metadata already (the expected values are the one guessed by composer here, except that it was not allowed to guess due to the outdated URLs).
I also changed the description:
- the right way to reference Symfony is ``Symfony``, not ``Symfony2`` (the version number ``2`` must be separated from the name)
- use ``2+`` as the standard is also OK for Symfony 3.
=> Update repo URLs in the composer.json

Symfony2/Tests/Objects/ObjectInstantiationUnitTest.inc
self is now properly handled as T_SELF, so the sniff needs to allow it.
=> Fix the instantiation sniff for PHPCS 2.8

Symfony2/Sniffs/Arrays/MultiLineArrayCommaSniff.php, Symfony2/Sniffs/Commenting/FunctionCommentSniff.php, Symfony2/Tests/Arrays/MultiLineArrayCommaUnitTest.inc, Symfony2/Tests/Arrays/MultiLineArrayCommaUnitTest.php
Also fix PHPCS error in Sniffs/Commenting/FunctionCommentSniff.php.
=> Fix Symfony2.Arrays.MultiLineArrayComma.Invalid false positives on empty arrays and arrays with comments in them

Symfony/ruleset.xml
leftover of migrating from phpcs 2 to 3.
unsure why all of a sudden this sniff stopped working for error type ``Missing`` (and unit tests didn't complain one bit about it), but this mod ensures missing function and class comments do show up again in the report.
=> fixes a bug where PEAR errors of type Missing wouldn't show up as errors

Symfony/Sniffs/Commenting/FunctionCommentSniff.php
as recorded in #69 
will raise an (additional) error if a protected or private function has no function comment
=> require function comments for every type of visibility

Symfony/Sniffs/Commenting/ClassCommentSniff.php, Symfony/ruleset.xml
will add an error if ``@package`` or ``@subpackage`` is used on class level
as recorded in #69
=> added @package and @subpackage to a blacklist for class annotations

Symfony/Sniffs/Functions/ArgumentsSniff.php
raises an error for multiline function declaration
as recorded in #66
i didn't include a unit test as they appear to be doing absolutely nothing during the build. will try to fix this in a seperate pr
=> Declare all the arguments on the same line as the method/function name

Symfony/Sniffs/Errors/ExceptionMessageSniff.php, Symfony/ruleset.xml
adds an error if ``T_STRING_CONCAT`` is used within an exception message
=> concat exception message with sprintf

Symfony/Sniffs/Errors/UserDeprecatedSniff.php
adds an error if a ``E_USER_DEPRECATED`` isn't silenced.
=> silence trigger_error of type E_USER_DEPRECATED by default

Symfony/Sniffs/Commenting/FunctionCommentSniff.php, Symfony/Sniffs/ControlStructure/YodaConditionsSniff.php
enforces ``Use Yoda conditions when checking a variable against an expression to avoid an accidental assignment inside the condition statement (this applies to ==, !=, ===, and !==).``
=> structure: yoda conditions

Symfony/Sniffs/ControlStructure/UnaryOperatorsSniff.php
Checks whether unary operators are defined on the right side of the variable.
fixes #29
=> structure: unary operators

Symfony/Sniffs/ControlStructure/IdenticalComparisonSniff.php
Checks for identical comparison and adds warning (as there's no way to know whether type juggling is needed) if not used.
=> structure: equality

README.md, Symfony/Sniffs/Commenting/LicenseSniff.php, UPGRADE-3.0.md
The license block has to be present at the top of every PHP file, before the namespace
recorded in #69
a sniff a day keeps the doctor away... 😎 
as mentioned in #69, this one just raises a warning as it appears to be specific to contributing to any symfony repository so shouldn't raise an error as far as i'm concerned. also no check whether the comment actual contains a ``license`` reference as placing any other comment prior to the namespace doesn't really make sense to me.
👍 for all the quick merges today @djoos, very much appreciated
=> documentation: license

Symfony/Sniffs/Commenting/LicenseSniff.php
where the license has been defined as a comment rather than a doc comment.
oops, this one slipped through
=> fixes a bug in the license sniff

Symfony/ruleset.xml
Omit the @return tag if the method does not return anything
recorded in #69 
this one just needed a severity modification in order for it to work...
=> documentation: return tag

Symfony/Sniffs/Commenting/AnnotationsSniff.php
Group annotations together so that annotations of the same type immediately follow each other, and annotations of a different type are separated by a single blank line
recorded in #69
=> dcoumentation: Group annotations together

Symfony/Sniffs/Commenting/AnnotationsSniff.php
fixes a bug where a single annotation spans multiple lines.
```php
/**
* @ORM\JoinTable(
*     joinColumns={@ORM\JoinColumn(name="// ...,
*     inverseJoinColumns={@ORM\JoinColumn(name="// ...
* )
*
* @SER\Groups("// ...
```
or with annotations which are not aliased
```php
/**
* @UniqueEntity(fields="email", message="user.email.duplicate")
* @UniqueEntity(fields="username", message="user.username.duplicate")
* // ...
```
should no longer trigger an error
=> annotation bug

Symfony/Sniffs/Commenting/TypeHintingSniff.php
For type-hinting in PHPDocs and casting, use bool (instead of boolean or Boolean), int (instead of integer), float (instead of double or real).
recorded in #68 
another ugly one 😎
=> Naming Conventions: type hints

Symfony/Sniffs/Functions/ReturnTypeSniff.php
Use return null; when a function explicitly returns null values and use return; when the function returns void values
=> structure: return type

Symfony/Sniffs/Formatting/ReturnOrThrowSniff.php, Symfony/Tests/Formatting/ReturnOrThrowUnitTest.inc
When closure is defined, this sniff should handle code inside closure.
=> ReturnOrThrowSniff doesn't handle Closures properly

composer.json
When installing phpcs through composer, this allows enforcing the usage of compatible versions.
I also fixed a few references to the repo URL.
=> Add a conflict rule to enforce compatible PHPCS versions

Symfony/Sniffs/Functions/ReturnTypeSniff.php
The ReturnTypeSniff is reporting errors with `explicitlyreturns` without a space between the two words.
=> Add missing space between words

Symfony/Sniffs/Functions/ReturnTypeSniff.php, Symfony/Tests/Functions/ReturnTypeUnitTest.inc, Symfony/Tests/Functions/ReturnTypeUnitTest.php
@mmoll @djoos 
could you review this PR?
And hopefully merge 😸 
This should fix #104,  #105, #134
=> check scope of return in ReturnTypeSniff

composer.json
codesniffer requirements moved from requirements-dev to requirements
to ensure presence of phpcs symlink in vendor/bin
fixes #142
=> move codesniffer requirements

Symfony/ruleset.xml
closes GH-42
closes GH-44
closes GH-107
=> Updated to ignore new lines for Squiz.Strings.ConcatenationSpacing.

Symfony/Sniffs/Objects/ObjectInstantiationSniff.php, Symfony/Tests/Objects/ObjectInstantiationUnitTest.inc, Symfony/Tests/Objects/ObjectInstantiationUnitTest.php
Double colon, object separator, etc...
closes GH-108
=> Add others allowed types for class creation

Symfony/Sniffs/Classes/PropertyDeclarationSniff.php, Symfony/Sniffs/Functions/ScopeOrderSniff.php, Symfony/Sniffs/Objects/ObjectInstantiationSniff.php, Symfony/Tests/Classes/PropertyDeclarationUnitTest.inc, Symfony/Tests/Classes/PropertyDeclarationUnitTest.php, Symfony/Tests/Functions/ScopeOrderUnitTest.inc, Symfony/Tests/Functions/ScopeOrderUnitTest.php, Symfony/Tests/Objects/ObjectInstantiationUnitTest.inc, Symfony/Tests/Objects/ObjectInstantiationUnitTest.php
Adds support for anonymous classes.
There is currently a proplem with PHP < 7: Since anonymous classes where added in PHP 7, running these Sniffs now generates a `Notice` due to the missing constant `T_ANON_CLASS`.
I'm unsure how to handle this: Ignore it, check for PHP-Versions < 7 or require PHP > 7.
=> Support anonymous classes (#153), closes GH-153

.travis.yml, Symfony/Sniffs/Whitespace/AssignmentSpacingSniff.php, Symfony/Tests/Whitespace/AssignmentSpacingUnitTest.inc.fixed
Not sure if the non-autofixable was intentional, but it seemed like an easy sniff to enable auto-fixing for.
Includes `.fixed` file to test the fixer.
=> Whitespace/AssignmentSpacing: make the error auto-fixable

Symfony/Sniffs/NamingConventions/ValidClassNameSniff.php
fixes an infinite loop which would occur when an interface
extends an improperly named interface ending with Exception as there's
no T_EXCEPTION token and the only way to sniff the correct naming of
an exception is to detect the classname when it's extending an exception.
nevertheless the incorrect naming of the extended class should raise an error in the extended class itself rather than in the class which is extending it
fixes #171
=> infinite loop fix

Symfony/Sniffs/Formatting/ReturnOrThrowSniff.php
fixes throwing an exception when inline control structures are used
this should be taken care of by the Generic.ControlStructures.InlineControlStructure
sniff so we can safely return
fixes #170
=> check for the presence of a scope closer

Symfony/Sniffs/Arrays/MultiLineArrayCommaSniff.php
Hello, 
I got this following error by running `vendor/bin/phpcbf`:
```bash
PHP Fatal error:  Uncaught PHP_CodeSniffer\Exceptions\RuntimeException: Increment on type bool has no effect, this will change in the next major version of PHP in /var/www/html/app/vendor/escapestudios/symfony2-coding-standard/Symfony/Sniffs/Arrays/MultiLineArrayCommaSniff.php on line 97 in /var/www/html/app/vendor/squizlabs/php_codesniffer/src/Runner.php:623
Stack trace:
#0 /var/www/html/app/vendor/escapestudios/symfony2-coding-standard/Symfony/Sniffs/Arrays/MultiLineArrayCommaSniff.php(97): PHP_CodeSniffer\Runner->handleErrors()
#1 /var/www/html/app/vendor/squizlabs/php_codesniffer/src/Files/File.php(519): Symfony\Sniffs\Arrays\MultiLineArrayCommaSniff->process()
#2 …
```
=> Fix MultiLineArrayCommaSniff for PHP 8.3

Symfony/ruleset.xml
Remove usage of sniff deprecated in phpcs 3.12.1 to be removed in phpcs 4.0.0
=> Remove usage of deprecated sniff
